set nocompatible
inoremap jk <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
syntax on
set encoding=utf-8
set wildmenu
set laststatus=2
call plug#begin()

Plug 'fatih/molokai'
Plug 'https://github.com/vim-syntastic/syntastic.git'
Plug 'tpope/vim-commentary'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'tpope/vim-surround'
Plug 'Raimondi/delimitMate'
Plug 'tpope/vim-repeat'
Plug 'ctrlpvim/ctrlp.vim'

call plug#end()


" colors
if $TERM == "xterm-256color" || $TERM == "screen-256color"
	set t_ut=
	set t_Co=256
endif

" Highlight trailing spaces
highlight ExtraWhitespace term=reverse ctermbg=6
au BufNewFile,BufRead * :match ExtraWhitespace /\s\+$/

" Open NERDTree Tabs quick toogle
nmap <leader>n :NERDTreeTabsToggle<CR>

"Options for the NERDTree
let g:NERDChristmasTree=1
let g:NERDTreeAutoDeleteBuffer=1
let g:NERDTreeChDirMode=2
let g:NERDTreeDirArrows=0
let g:NERDTreeShowBookmarks=1
let g:NERDTreeShowHidden=1

"Options for delimitmate
let delimitMate_expand_cr = 2
let delimitMate_expand_space = 2

"Syntastic
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'

nnoremap ; :
vnoremap ; :

" Moves between splits the easy way
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

nnoremap <leader>i :set paste<CR>i

augroup paste_helper
	" Clear the autocmd
	autocmd!
	" set not paste in normal mode
	autocmd InsertLeave * set nopaste
augroup END

" Navigate through tabs / buffers
nnoremap gl	:tabnext<CR>
nnoremap gh	:tabprev<CR>
nnoremap gL	:bnext<CR>
nnoremap gH	:bprev<CR>

" Highlight trailing spaces
highlight ExtraWhitespace term=reverse ctermbg=12
au BufNewFile,BufRead * :match ExtraWhitespace /\s\+$/

" More natural splits
set splitright
set splitbelow

colorscheme zenburn

" Open NERTree if vim start with no file
autocmd vimenter * if !argc() | let g:nerdtree_tabs_open_on_console_startup=1 | endif

highlight ExtraWhitespace term=reverse ctermbg=196
au BufNewFile,BufRead * :match ExtraWhitespace /\s\+$/

" Show tabs and end of lines
:set listchars=tab:▸\ ,eol:¬,trail:·
