set nocompatible
inoremap jk <ESC>
let mapleader = "\<Space>"
filetype plugin indent on
syntax on
set encoding=utf-8
set wildmenu
set laststatus=2
call plug#begin()

Plug 'https://github.com/vim-syntastic/syntastic.git'
Plug 'tpope/vim-commentary'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
call plug#end()


" Highlight trailing spaces
highlight ExtraWhitespace term=reverse ctermbg=12
au BufNewFile,BufRead * :match ExtraWhitespace /\s\+$/

" Open NERDTree Tabs quick toogle
nmap <leader>n :NERDTreeTabsToggle<CR>

"Options for the NERDTree
let g:NERDChristmasTree=1
let g:NERDTreeAutoDeleteBuffer=1
let g:NERDTreeChDirMode=2
let g:NERDTreeDirArrows=0
let g:NERDTreeShowBookmarks=1
let g:NERDTreeShowHidden=1

" Moves between splits the easy way
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

nnoremap <leader>i :set paste<CR>i

augroup paste_helper
	" Clear the autocmd
	autocmd!
	" set not paste in normal mode
	autocmd InsertLeave * set nopaste
augroup END

" Navigate through tabs / buffers
nnoremap gl	:tabnext<CR>
nnoremap gh	:tabprev<CR>
nnoremap gL	:bnext<CR>
nnoremap gH	:bprev<CR>

" More natural splits
set splitright
set splitbelow

" Open NERTree if vim start with no file
autocmd vimenter * if !argc() | let g:nerdtree_tabs_open_on_console_startup=1 | endif
